server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
      - id: employeeModule
        uri: http://localhost:8088/
        predicates:
        - Path=/employee/**
      - id: consumerModule
        uri: http://localhost:8082/
        predicates:
        - Path=/consumer/**